### ISSUE TITLE
Is there a way to reuse operation parameters?

### ISSUE THREAD

**Issue by Napas** [guzzle/guzzle-services#140]
```
baseUri: 'http://localhost`
operations:
    createUser:
        uri: /user
        httpMethod: POST
        responseModel: userModel
        parameters:
            username:
                type: string
                required: true
                location: json
            email:
                type: string
                required: true
                location: json
    createUsers:
        uri: /users
        httpMethod: POST
        parameters:
            payload:
                type: array
                location: json
```

Is there a way to tell that payload in createUsers operation has an array with same parameters as createUser operation?

And can operation send array of objects without assigning it to the payload (or any other) key(s)?
